version: '2.1'
services:
    mysql:
        image: mysql
        build: ./db
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always
        healthcheck:
            test: "exit 0"
    app:
        build: .
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - "${PORT}:${PORT}"
        links:
            - mysql:mysql
        volumes:
            - ./:/usr/src/app