export const TOGGLE_MUTE = 'TOGGLE_MUTE';
export const TOGGLE_VIDEO = 'TOGGLE_VIDEO';

export const GET_SESSION_START = 'GET_SESSION_START';
export const GET_SESSION_SUCCESS = 'GET_SESSION_SUCCESS';
export const GET_SESSION_FAILURE = 'GET_SESSION_FAILURE';

export const CREATE_SESSION_START = 'CREATE_SESSION_START';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_FAILURE = 'CREATE_SESSION_FAILURE';

export const END_SESSION_START = 'END_SESSION_START';
export const END_SESSION_SUCCESS = 'END_SESSION_SUCCESS';
export const END_SESSION_FAILURE = 'END_SESSION_FAILURE';

export const JOIN_SESSION_START = 'JOIN_SESSION_START';
export const JOIN_SESSION_SUCCESS = 'JOIN_SESSION_SUCCESS';
export const JOIN_SESSION_FAILURE = 'JOIN_SESSION_FAILURE';

export const LEAVE_SESSION_START = 'LEAVE_SESSION_START';
export const LEAVE_SESSION_SUCCESS = 'LEAVE_SESSION_SUCCESS';
export const LEAVE_SESSION_FAILURE = 'LEAVE_SESSION_FAILURE';

export const GET_ACTIVE_USERS_START = 'GET_ACTIVE_USERS_START';
export const GET_ACTIVE_USERS_SUCCESS = 'GET_ACTIVE_USERS_SUCCESS';
export const GET_ACTIVE_USERS_FAILURE = 'GET_ACTIVE_USERS_FAILURE';

export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const SET_USER_KEY = 'SET_USER_KEY';

export const ADD_STREAM = 'ADD_STREAM';
export const UPDATE_STREAM = 'UPDATE_STREAM';
export const UPDATE_STREAM_ELEMENT = 'UPDATE_STREAM_ELEMENT';
export const REMOVE_STREAM = 'REMOVE_STREAM';